# Data Cleaning

In [1]:
import pandas as pd

## 1. Leyendo el dataframe

In [2]:
df = pd.read_csv('../data/raw/social_media_vs_productivity.csv')
df

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,8,False,False,4,11,21.927072,6.336688
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,5.103897,0.671519,7,True,True,2,25,0.000000,3.412427
2,32,Male,Finance,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,8.583222,0.624378,0,True,False,3,17,10.322044,2.474944
3,60,Female,Unemployed,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,6.052984,1.204540,1,False,False,0,4,23.876616,1.733670
4,25,Male,IT,NaN,Telegram,66,6.214096,8.868753,NaN,7.0,5.405706,1.876254,1,False,True,1,30,10.653519,9.693060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,34,Female,Health,1.877297,Facebook,59,10.226358,3.348512,3.465815,8.0,5.480462,1.412655,9,False,False,4,5,21.776927,NaN
29996,39,Male,Health,4.437784,Instagram,46,4.692862,8.133213,6.659294,8.0,3.045393,0.148936,3,False,False,1,29,4.111370,6.155613
29997,42,Male,Education,17.724981,TikTok,64,10.915036,8.611005,8.658912,5.0,5.491520,1.224296,10,False,False,1,2,1.888315,6.285237
29998,20,Female,Education,3.796634,Instagram,56,6.937410,7.767076,6.895583,8.0,6.816069,0.234483,1,False,False,2,9,12.511871,7.854711
29999,44,Male,Unemployed,NaN,Twitter,70,8.069883,6.311227,5.402726,3.0,6.765248,0.993090,5,False,True,1,4,6.324954,7.388790

## 2. Rellenando datos nulos

In [3]:
# Vemos el porcentaje de datos nulos que hay en cada columna
df_nulls = df.isnull().sum().reset_index()
df_nulls.rename(columns={0 : 'count'}, inplace = True)
df_nulls['count'] = (df_nulls['count'] / df_nulls['count'].sum() * 100).round(2)
df_nulls

                             index  count
0                              age   0.00
1                           gender   0.00
2                         job_type   0.00
3          daily_social_media_time  17.08
4       social_platform_preference   0.00
5          number_of_notifications   0.00
6               work_hours_per_day   0.00
7     perceived_productivity_score   9.97
8        actual_productivity_score  14.61
9                     stress_level  11.76
10                     sleep_hours  16.05
11        screen_time_before_sleep  13.66
12              breaks_during_work   0.00
13                 uses_focus_apps   0.00
14   has_digital_wellbeing_enabled   0.00
15      coffee_consumption_per_day   0.00
16  days_feeling_burnout_per_month   0.00
17            weekly_offline_hours   0.00
18          job_satisfaction_score  16.87

In [4]:
# Hacemos una función para rellenar los valores nulos a partir de combinaciones de columnas importantes
def fillnancombinations(column : str):

    """
    Fill NaN values in the specified column using the mean of groups defined by categorical columns.
    """

    return df[column].fillna(
        df.groupby(['gender', 'job_type', 'social_platform_preference'])[column].transform('mean')
    )

In [5]:
## Rellenando las columnas con datos nulos
df['daily_social_media_time'] = fillnancombinations('daily_social_media_time')

df['perceived_productivity_score'] = fillnancombinations('perceived_productivity_score')

df['actual_productivity_score'] = fillnancombinations('actual_productivity_score')

df['stress_level'] = fillnancombinations('stress_level')

df['sleep_hours'] = fillnancombinations('sleep_hours')

df['screen_time_before_sleep'] = fillnancombinations('screen_time_before_sleep')

df['job_satisfaction_score'] = fillnancombinations('job_satisfaction_score')

In [6]:
df

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,8,False,False,4,11,21.927072,6.336688
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,5.103897,0.671519,7,True,True,2,25,0.000000,3.412427
2,32,Male,Finance,3.150652,Twitter,57,7.910952,3.861762,3.474053,4.0,8.583222,0.624378,0,True,False,3,17,10.322044,2.474944
3,60,Female,Unemployed,3.318476,Facebook,59,6.355027,2.916331,1.774869,6.0,6.052984,1.204540,1,False,False,0,4,23.876616,1.733670
4,25,Male,IT,3.207723,Telegram,66,6.214096,8.868753,5.073391,7.0,5.405706,1.876254,1,False,True,1,30,10.653519,9.693060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,34,Female,Health,1.877297,Facebook,59,10.226358,3.348512,3.465815,8.0,5.480462,1.412655,9,False,False,4,5,21.776927,4.998575
29996,39,Male,Health,4.437784,Instagram,46,4.692862,8.133213,6.659294,8.0,3.045393,0.148936,3,False,False,1,29,4.111370,6.155613
29997,42,Male,Education,17.724981,TikTok,64,10.915036,8.611005,8.658912,5.0,5.491520,1.224296,10,False,False,1,2,1.888315,6.285237
29998,20,Female,Education,3.796634,Instagram,56,6.937410,7.767076,6.895583,8.0,6.816069,0.234483,1,False,False,2,9,12.511871,7.854711
29999,44,Male,Unemployed,3.151979,Twitter,70,8.069883,6.311227,5.402726,3.0,6.765248,0.993090,5,False,True,1,4,6.324954,7.388790

## 3. Verificando que no haiga valores nulos

In [8]:
# Valores nulos
df.isnull().sum()

age                               0
gender                            0
job_type                          0
daily_social_media_time           0
social_platform_preference        0
number_of_notifications           0
work_hours_per_day                0
perceived_productivity_score      0
actual_productivity_score         0
stress_level                      0
sleep_hours                       0
screen_time_before_sleep          0
breaks_during_work                0
uses_focus_apps                   0
has_digital_wellbeing_enabled     0
coffee_consumption_per_day        0
days_feeling_burnout_per_month    0
weekly_offline_hours              0
job_satisfaction_score            0
dtype: int64

## 5. Exportando datos limpios

In [9]:
df.to_csv('../data/processed/social_media_vs_productivity_clean.csv', index=False)